./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --enable-fpm \
  --with-mysql \
  --with-mcrypt \
  --with-zlib \
  --with-gd \
  --with-png-dir \
  --with-zlib-dir \
  --with-jpeg-dir \
  --with-config-file-path=/etc
